server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    url: jdbc:mysql://localhost:3306/order_system?useSSL=false&serverTimezone=UTC
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  main:
    allow-circular-references: true
  mail:
    host: smtp.qq.com
    port: 25
    username: 2985496686@qq.com
    password: vvzgmygsnqtlddic
    from: 2985496686@qq.com



mybatis-plus:
  type-aliases-package: com.entity # 别名扫描包
  # mapper-locations: classpath*:mapper/*.xml
logging:
  level:
    com: debug

