server:
  port: 8081
spring:
  mail:
    host: smtp.163.com
    password: JIRODMMFZZCHBFNA
    username: g2985496686@163.com
    from: g2985496686@163.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  application:
    name: hmdp
  datasource:
    url: jdbc:mysql://localhost:3306/order_system?useSSL=false&serverTimezone=UTC
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.1.169
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    password: 111111
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  main:
    allow-circular-references: true

mybatis-plus:
  type-aliases-package: com.entity # 别名扫描包
  # mapper-locations: classpath*:mapper/*.xml
logging:
  level:
    com: debug





